### ISSUE TITLE
toJWK fails to be imported by JOSE lib

### ISSUE THREAD

**Issue by vongohren** [digitalcredentials/ed25519-verification-key-2020#5]
Hi! Im using this library to support 2020 version of ed25519 keys.

# Problem
Im using, https://www.npmjs.com/package/jose, where I import a JWK https://github.com/panva/jose/blob/HEAD/docs/functions/key_import.importJWK.md#readme to do JOSE work.

But this current library, which has a `toJWK` method on the privateKey, fails to be imported by the JOSE lib.

Before this call to `toJWK`, i do run the `.from` on a rawKeyJson that looks like this:

```
{
  id: "#Mkfxwd3x",
  controller: "did:peer:2.Vz6Mkfxwd3xWMeSvsgiU2MuAyshy5rXyWW1e3rDnUg1vCs2o3.SeyJpZCI6IiNkaWRjb21tIiwidCI6ImRtIiwicyI6Imh0dHBzOi8vZGV2LW9wZW4tbWVzc2FnZXMtYXBpLWx0aDRnb3dkeXEtZXcuYS5ydW4uYXBwL21lc3NhZ2VzIiwiYSI6WyJkaWRjb21tL3YyIl19",
  type: "Ed25519VerificationKey2020",
  publicKeyMultibase: "z6Mkfxwd3xWMeSvsgiU2MuAyshy5rXyWW1e3rDnUg1vCs2o3",
  privateKeyMultibase: "zrv33yPZvxDNqgEibiNh7WsiJtwPKbFDqm3LZMkTZZqAKD2oNgc5R8XbhGZsEwCV32cFUmjWLmiSTsrvvqetXyDA4zu",
}
```

Here is the key im able to produce by using `toJsonWebKey2020` and `toJWK` and combine it a JWK with privatekey. Then its alos the private key value im testing with.

```
{
  "@context": "https://w3id.org/security/jws/v1",
  id: "did:peer:2.Vz6Mkfxwd3xWMeSvsgiU2MuAyshy5rXyWW1e3rDnUg1vCs2o3.SeyJpZCI6IiNkaWRjb21tIiwidCI6ImRtIiwicyI6Imh0dHBzOi8vZGV2LW9wZW4tbWVzc2FnZXMtYXBpLWx0aDRnb3dkeXEtZXcuYS5ydW4uYXBwL21lc3NhZ2VzIiwiYSI6WyJkaWRjb21tL3YyIl19#uBei8Do8DTpJEEXR7ikQLYin_4KRt4NPSMRO5ZJWSc0",
  type: "JsonWebKey2020",
  controller: "did:peer:2.Vz6Mkfxwd3xWMeSvsgiU2MuAyshy5rXyWW1e3rDnUg1vCs2o3.SeyJpZCI6IiNkaWRjb21tIiwidCI6ImRtIiwicyI6Imh0dHBzOi8vZGV2LW9wZW4tbWVzc2FnZXMtYXBpLWx0aDRnb3dkeXEtZXcuYS5ydW4uYXBwL21lc3NhZ2VzIiwiYSI6WyJkaWRjb21tL3YyIl19",
  privateKeyJwk: {
    crv: "Ed25519",
    kty: "OKP",
    x: "FnZHtzuBabRCjqhH6lcyC5XS2eOdJ9sMhJmMYVNq-7I",
    d: "eMu1bCoSfNOYcqe32lnm7_47MONTWY82mzdHg5JzewEWdke3O4FptEKOqEfqVzILldLZ450n2wyEmYxhU2r7sg",
  },
  publicKeyJwk: {
    crv: "Ed25519",
    kty: "OKP",
    x: "FnZHtzuBabRCjqhH6lcyC5XS2eOdJ9sMhJmMYVNq-7I",
  },
}
```

The error im getting from JOSE lib is

`Error: error:1010A066:elliptic curve routines:ecx_key_op:invalid encoding`

# My expectations 
Be able to export from this library and import JWK into JOSE lib.
Have encoding to work properly

**Comment by dmitrizagidulin** [comment]
@vongohren - oh interesting, I wonder what's up with the encoding.
I'll take a look.
(Thanks for the heads up).

**Comment by vongohren** [comment]
@dmitrizagidulin cool cool, thanks. By all means, I can do something wrong here, but Im just following methods from this lib right before I take it to jose.

**Comment by dmitrizagidulin** [comment]
@vongohren oh, hey, can you also paste the code you're invoking the JOSE lib with? Just the whole end-to-end that causes the error.

**Comment by vongohren** [comment]
Yeah something along these lines @dmitrizagidulin 
```
     import * as jose from 'jose';
     import {Ed25519VerificationKey2020} from '@digitalcredentials/ed25519-verification-key-2020';

     // Raw key is the key pasted above
    const key = await Ed25519VerificationKey2020.from(rawKey);
    const publicJwk = await key.toJsonWebKey2020()
    const jwk = {
      privateKeyJwk: key.toJwk({privateKey: true}),
      ...publicJwk
    }
    const privateKey = await jose.importJWK(jwk.privateKeyJwk,'ES256')
   // Fails on import


```

**Comment by dmitrizagidulin** [comment]
@vongohren ah, ok, so, the first thing that comes to mind is -- there's a mismatch in key types, right.

This lib only deals with Ed25519 keys, but you're trying to import them as ES256 keys, which is a different curve. You'll need either a ecdsa-secp256r1 type library for that, OR you need to import it to the jose library using the Ed25519 algorithm, which would be `jose.importJWK(jwk.privateKeyJwk, 'EdDSA')` (I'm not sure if that lib specifically supports that curve though).

**Comment by dmitrizagidulin** [comment]
@vongohren yeah, looks like the `jose` lib has support for `EdDSA`, so try that.

**Comment by vongohren** [comment]
@dmitrizagidulin so excuse my lack of knowledge in the different crypto types. 
But the thing is that i have already been doing this, and it has been working, I have been using in OIDC JFF interop. There Im using https://www.npmjs.com/package/@transmute/ed25519-key-pair. This lib does not support the Ed25519VerificationKey2020 version directly so had to go for this lib for Ed25519VerificationKey2020.

This is were the troubles of the same code started to occur

What I do with the transmute Ed25519VerificationKey2018 lib is
`const jwk = await key.export({privateKey: true, type:'JsonWebKey2020'});`
And all is good and it is working to IMPORT with 
`const privateKey = await jose.importJWK(fullJwkKey.privateKeyJwk,'ES256')`

So since 2020 is using multibase, should it be a different key version for jose?

That is mainly why i raised an issue. And the lenght of the private keys are very different from eachother when I use the 2018 version and 2020 version.

**Comment by dmitrizagidulin** [comment]
@vongohren oh interesting! That shouldn't be working.. Those are different key types...

**Comment by dmitrizagidulin** [comment]
@vongohren I'll take a look at the different key length issue and double-check the encoding, see if that provides any insight.

**Comment by vongohren** [comment]
@dmitrizagidulin great stuff! I will not be online for long so please leave a descriptive message if there is anything else I should try :D

**Comment by dmitrizagidulin** [comment]
@vongohren - I'd be curious if you could try importing to the jose library with the proper key alg, `EdDSA` -- does it still error?

**Comment by vongohren** [comment]
@dmitrizagidulin So I changed and it worked for the other keys, that are 2018 variants and being created by the transmute lib. But still not for this library.

I have in my sign JWT code also that im creating protected header with `EdDSA`, so that alg and `ES256`seems interoparble for the 2018 key variant, but not this library that produces 2020

**Comment by vongohren** [comment]
@dmitrizagidulin I know this is IIW time and stuff, but any thoughts on how this can progress? Should I ask digital bazaar? as this is a fork from there?

**Comment by dmitrizagidulin** [comment]
@vongohren - heh, yeah, apologies, currently distracted by IIW stuff. 
Yeah, it is a fork of the D.B. library -- feel free to ask there too!

**Comment by vongohren** [comment]
Following this up :D

**Comment by dmitrizagidulin** [comment]
@vongohren - I found the cause, there was a bug in JWK import and export, in this lib.
PR #7 should fix it.

Here's the code it enables:

```js
      // generated by 'jose' lib via `await jose.exportJWK(await jose.generateKeyPair('EdDSA'))`
      const exampleJoseKey = {
        crv: 'Ed25519',
        d: 'y71N3tdun63bo9OBHXuI03qaV3eY3kL1ypoG8tFy4LI',
        x: 'JOVEKqgcoSaDbYimIWoJHcvlZefVDQJXtKMmSRBHCHU',
        kty: 'OKP'
      }

      const keyPair = await Ed25519VerificationKey2020.fromJsonWebKey2020({
        type: 'JsonWebKey2020',
        publicKeyJwk: {...exampleJoseKey},
        privateKeyJwk: {...exampleJoseKey}
      })

      const exportedJwk: any = await keyPair.toJwk({publicKey: true, privateKey: true})

      expect(exportedJwk).to.eql({
          crv: 'Ed25519',
          d: 'y71N3tdun63bo9OBHXuI03qaV3eY3kL1ypoG8tFy4LI',
          x: 'JOVEKqgcoSaDbYimIWoJHcvlZefVDQJXtKMmSRBHCHU',
          kty: 'OKP'
      })

      const importedJoseKey = await jose.importJWK(exportedJwk, 'EdDSA')
      expect(await jose.exportJWK(importedJoseKey)).to.eql({
        crv: 'Ed25519',
        d: 'y71N3tdun63bo9OBHXuI03qaV3eY3kL1ypoG8tFy4LI',
        x: 'JOVEKqgcoSaDbYimIWoJHcvlZefVDQJXtKMmSRBHCHU',
        kty: 'OKP'
      })
```

**Comment by vongohren** [comment]
@dmitrizagidulin cool cool, that sure is great! I will wait for the merge to include in my code :D Thanks for looking into this!

**Comment by vongohren** [comment]
Closing this now
